name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install
      
      - name: Fix Vulnerabilities
        if: ${{ github.repository == 'frknmydn/demo-notification' }}
        run: npm audit fix --force
      
      - name: Run Security Audit
        if: ${{ github.repository == 'frknmydn/demo-notification' }}
        run: npm audit --audit-level=low
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
      - name: Trigger Notification Step
        if: ${{ github.repository == 'frknmydn/demo-notification' }}
        run: echo "tests completed"
